# Generated by Django 2.1.1 on 2019-05-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('status_type', models.IntegerField()),
                ('percent', models.FloatField(default=0.0)),
            ],
        ),
    ]
