# Generated by Django 2.1.1 on 2019-05-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
