# Generated by Django 2.1.1 on 2019-05-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_progress_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='status_type',
            field=models.IntegerField(null=True),
        ),
    ]
